setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  #_source.enabled: false

#================================ General =====================================

# Optional fields that you can specify to add additional information to the
# output.
fields:
  env: ELK-UAT

metricbeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
  #  - process_summary
    #- socket_summary
    - core
    - diskio
    #- socket
  
  process.cgroups.enabled: false
  process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory
    
  enabled: true
  period: 1m
  cpu_ticks: true


- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  filesystem.ignore_types: [nfs, smbfs, autofs]

# metricset uptime  and process_summary unavailable for 5.6.16
#- module: system
 # period: 15m
 # metricsets:
  #  - uptime



#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "image","memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 30s

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  hosts: ["10.2.5.21:9200"]
  #template.name: "metricbeat"
  #template.path: "metricbeat.template.json"
  #template.overwrite: false
  indices:
    - index: "metricbeat-elk-uat-%{[event.module]}-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "docker"

    - index: "metricbeat-elk-uat-%{[event.module]}-%{+yyyy.MM.dd}"
      when.equals:
        event.module: "system"

#============================== Kibana =====================================

# Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
# This requires a Kibana endpoint configuration.

setup.kibana:
  host: "10.2.5.21:5601"
  setup.dashboards.enabled: true
#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_cloud_metadata: ~

#============================== Dashboards =====================================
# These settings control loading the sample dashboards to the Kibana index. Loading
# the dashboards is disabled by default and can be enabled either by setting the
# options here, or by using the `-setup` CLI flag.

logging.level: warning
#logging.to_files: true
#logging.to_syslog: false
#logging.files:
 # path: /var/log/metricbeat
  #name: metricbeat.log
  #keepfiles: 2
  #permissions: 0644

